name: scrape
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  scrape_and_email:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install all necessary packages
        run: pip install requests beautifulsoup4
      - name: Run the scraping script
        run: python scrape.py
      - name: Commit and push and email if content changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" &&
            export COMMIT_HASH=$(git rev-parse HEAD) &&
            exit 0
          git push
